sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - composer test
  - composer cs